### ISSUE TITLE
Who on a earth want to run stream in routes?

### ISSUE THREAD

**Issue by thewebdevelopment** [imanghafoori1/laravel-video#10]
Not body like to use such way in any project.Proper controller and view approach make sense.

`
Route::get('/home', function () {
    $path = public_path('vid.mp4');
    
    VideoStreamer::streamFile($path);
});

`

**Comment by imanghafoori1** [comment]
of course, this is the simplest way to run an example for testing and understand the bare bone of it.

**Comment by jbenavidesv87** [comment]
@imanghafoori1, can you give us an example of how to use this to stream into a <video> element?

**Comment by SomeRandomGithubUserXd** [comment]
Is the brain of yours dead? It's just a demo how you can stream a video. You can put it in the controller. Learn how to understand docs first, then write an issue
