### ISSUE TITLE
issue with using external urls for files

### ISSUE THREAD

**Issue by alirezaporthos** [imanghafoori1/laravel-video#18]
the mime_content_type($filePath) function in VideoStreamer.php line 33 accepts only a local url. if you use a external url for your video it will cause a problem.

can we do sth so it could work with external urls too?

**Comment by quaque-ghy** [comment]
Any solution please? video URL from s3 or digital ocean spaces still not working.

**Comment by imanghafoori1** [comment]
This package is designed to work only with local file system, you first have to copy the streaming file from s3 onto your file and then play it. after that, you are free to delete the file.
