### ISSUE TITLE
streamVideoFile does not exists, did you mean Stream?

### ISSUE THREAD

**Issue by davidbonting** [imanghafoori1/laravel-video#2]
On a fresh installation of Laravel, your example did not workout for me. I did solve it, by looking at your code and manually doing the same thing in my web.php routes:
```
            $stream = new Iman\Streamer\VideoStreamer($path);
            return $stream->start();
```

But this:
```
return response()->streamVideoFile($path);
```

Didn't workout. Maybe more people are experience this issue? Or do macro's never work directly from web.php?

But all in all, great package!

**Comment by imanghafoori1** [comment]
hmmmmmm, I have to test it out. Honestly since I have too many packages I am not that much accurate these days.

**Comment by Keftaa** [comment]
I am experiencing the same issue on Laravel 5.7

**Comment by imanghafoori1** [comment]
could you please go to the vendor folder and change the source code like this ?
```
    public function register()
    {
        Response::macro('streamVideoFile', function ($filePath) {
            return response()->stream(function () use ($filePath) {
                $stream = new VideoStreamer($filePath);
                return $stream->start();
            });
        });
    }
```

if it did not work then test this :
```php
    public function register()
    {
        Response::macro('streamVideoFile', function ($filePath) {
                $stream = new VideoStreamer($filePath);
                return $stream->start();
        });
    }
```

and report me the result, thanks

**Comment by YoungMayor** [comment]
I am having a mega issue using remote url's with this package. 
That is: 
```

$videoPath = "videos/sample_vid.mp4";
$stream = new Iman\Streamer\VideoStreamer($videoPath);
return $stream->start();

```
works fine but 

```

$videoPath = "http://examplesite.com/videos/sample_vid.mp4";
$stream = new Iman\Streamer\VideoStreamer($videoPath );
return $stream->start();

```
doesn't work

**Comment by imanghafoori1** [comment]
I highly recommend you to install version 2.x 
there is an other important fix which causes the video to stream more gradually.

**Comment by davidbonting** [comment]
Sorry for the late reply, but 2.x indeed works, thanks!

`Iman\Streamer\VideoStreamer::streamFile($path);`
