### ISSUE TITLE
Unable to stream videos from a remote host

### ISSUE THREAD

**Issue by YoungMayor** [imanghafoori1/laravel-video#4]
I am having a mega issue using remote url's with this package. 
That is: 
```

$videoPath = "videos/sample_vid.mp4";
$stream = new Iman\Streamer\VideoStreamer($videoPath);
return $stream->start();

```
works fine but 

```

$videoPath = "http://examplesite.com/videos/sample_vid.mp4";
$stream = new Iman\Streamer\VideoStreamer($videoPath );
return $stream->start();

```
doesn't work

**Comment by imanghafoori1** [comment]
Of course it is designed to work with local file system only. You want to get the file on the fly from an other server? 
@YoungMayor

**Comment by YoungMayor** [comment]
Yes Iman, if it would be possible to modify the package to allow for remote otf streaming, it would be a better upgrade

**Comment by imanghafoori1** [comment]
It would be very tricky, maybe not possible in many cases, 
I think you should first download the entire file to your server and start streaming it. 

It seems you want to only proxy the content from another server

**Comment by YoungMayor** [comment]
Alright, I'd do just that

**Comment by imanghafoori1** [comment]
![Uploading image.png…]()
