### ISSUE TITLE
ERR_CONTENT_LENGTH_MISMATCH 206 (Partial Content) error

### ISSUE THREAD

**Issue by seyed-me** [imanghafoori1/laravel-video#7]
This package works fine but logs ERR_CONTENT_LENGTH_MISMATCH 206 (Partial Content) error in the console and failed status in browsers devTools network tab.

**Comment by imanghafoori1** [comment]
Please also provide an screen shot of the error message.
Thanks

**Comment by seyed-me** [comment]
![chrome_SAgWuroJAS](https://user-images.githubusercontent.com/47121888/75166003-7b801c80-5738-11ea-8b7e-92b3c584e3fd.png)
![chrome_ORys1tcf1f](https://user-images.githubusercontent.com/47121888/75166012-7d49e000-5738-11ea-80a1-6b6c42fd73bf.png)

**Comment by davidbonting** [comment]
I'm experience the same during development. But on the live server the video won't load on the first request. Once I refresh the page, it does work.

**Comment by imanghafoori1** [comment]
I think you should change the web server settings.
https://github.com/expressjs/express/issues/3392#issuecomment-354073432

https://stackoverflow.com/questions/24434231/err-content-length-mismatch-when-loading-audio

please also check for the same issue in Firefox and etc (not only chrome).

**Comment by seyed-me** [comment]
There is no problem with Firefox and Brave and Edge (both based on Chromium) have the same problem. unfortunately, I have no access to Apache configuration on this app yet to test this solution. Thanks.

**Comment by imanghafoori1** [comment]
I think that chrome is wrong about the error message.
As the stack over flow say it is going too smart.

Anyway if the end user is expriancing no error it is ok.

I suggest to tinker with the buffer size in the config file. To see what
will happen.

**Comment by seyed-me** [comment]
I tried this and this problem was solved:

[https://codesamplez.com/programming/php-html5-video-streaming-tutorial](url)

**Comment by imanghafoori1** [comment]
could you please open up a pull request ?
Since I am busy for now.

**Comment by seyed-me** [comment]
OK.

**Comment by imanghafoori1** [comment]
The PR removes a feature but I think I found the real issue.

**Comment by seyed-me** [comment]
There is another problem that I do not know why it happens. And the problem is that in the last version (2.0.2) most of the times a stream request canceled and the web page blinks and the player does not work. There is no problem with the snippet that I mentioned.

![chrome_YK3cCmN40K](https://user-images.githubusercontent.com/47121888/77255245-aa2fdb00-6c83-11ea-8e9f-360842ed37d5.png)

**Comment by imanghafoori1** [comment]
So the current version must be ok for now
Thanks for feed back
